CREATE TABLE IF NOT EXISTS b_task_curator (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TASK_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CREATED_BY INT,
    DATE_CREATE DATETIME,
    UNIQUE KEY unique_task_user (TASK_ID, USER_ID),
    KEY idx_user (USER_ID),
    KEY idx_task (TASK_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;